# Generated by Django 3.0.1 on 2019-12-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.CharField(blank=True, help_text='title of a post', max_length=512),
        ),
    ]
