# Generated by Django 3.0.4 on 2020-03-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='html',
            field=models.TextField(help_text='content for quick view', null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(help_text='content for editor mode'),
        ),
    ]
