# Generated by Django 3.0.4 on 2020-04-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200324_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_shareable',
            field=models.BooleanField(default=False, help_text='mark if the article was able to share'),
        ),
    ]
